<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__general-imgcol</name>
   <tag></tag>
   <elementGuidId>1a035587-7fb2-4916-94c3-2938c47ad507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div[2]/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.general-imgcol</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>42d61051-ff22-4668-90a1-f7fb4797c2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>general-imgcol</value>
      <webElementGuid>586e49e2-2c51-4348-b9d6-407e596f20bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;card-page&quot;]/div[@class=&quot;graph-result-card&quot;]/div[@class=&quot;graph-similar graph-container&quot;]/div[@class=&quot;graph-similar-list&quot;]/div[@class=&quot;general-waterfall&quot;]/div[@class=&quot;general-imgcol&quot;]</value>
      <webElementGuid>ebcd755d-1cfe-4a83-a7f0-4985274ca81c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div</value>
      <webElementGuid>2a426aff-d12d-4588-8e3c-fa321d4363d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='相似图片'])[1]/following::div[3]</value>
      <webElementGuid>b4cffbfd-bf9d-4232-8c87-5e4b195839a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='undefined'])[4]/following::div[8]</value>
      <webElementGuid>e66dfb68-7f3d-42b9-bb83-92fbbc8d39be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='正在加载...'])[1]/preceding::div[5]</value>
      <webElementGuid>ac78c78b-ca5f-4e2c-8158-29670b994cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results :('])[1]/preceding::div[6]</value>
      <webElementGuid>0d614036-8ff9-4ea3-8831-9d8b6eca1268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>e6bf8bc1-a01f-44d4-96cf-9ed6c3b130d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
