<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__soutu-btn</name>
   <tag></tag>
   <elementGuidId>14824281-9a1e-4cbc-b386-63997aea8f23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.soutu-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c89dcab3-1c31-4d74-95bd-468875af8dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>soutu-btn</value>
      <webElementGuid>e0b2bb9b-a29c-437a-865b-095d7934430d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/span[@class=&quot;bg s_ipt_wr new-pmd quickdelete-wrap&quot;]/span[@class=&quot;soutu-btn&quot;]</value>
      <webElementGuid>0013053e-782c-40f2-9a05-bfcf64d52b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/span/span</value>
      <webElementGuid>ee6955b5-2d8b-4f02-87b5-8e800e96511f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>36518e38-348b-4294-9aef-709c0fea2517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
