<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_knownDialog</name>
   <tag></tag>
   <elementGuidId>ea37b901-0427-4f54-ad5f-b1658e0658f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.graph-guide-info-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/div/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0db7012-f5f4-4fee-880e-b094556b4d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>graph-guide-info-btn</value>
      <webElementGuid>73598fcd-fe45-4847-ae75-d1d06b4b5ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            知道啦
        </value>
      <webElementGuid>bede13ad-3c09-4acb-b9db-87e6266ac34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;card-page&quot;]/div[@class=&quot;graph-result-card&quot;]/div[@class=&quot;graph-header&quot;]/div[@class=&quot;graph-header-info&quot;]/div[@class=&quot;graph-header-top&quot;]/div[@class=&quot;graph-container&quot;]/div[@class=&quot;graph-guide-container is-result&quot;]/div[@class=&quot;graph-guide-info&quot;]/div[@class=&quot;graph-guide-info-btn&quot;]</value>
      <webElementGuid>3414c29c-8036-4266-b08b-bd17e6ae8243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>d2580820-02a3-411b-8095-499693fdfd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='手机端拍照提取文字后，可一键传输到电脑端进行复制编辑。'])[1]/following::div[1]</value>
      <webElementGuid>2e359c6c-ed3c-43d6-ad9f-53760426977c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='解放双手的文档编辑神器来了！'])[1]/following::div[2]</value>
      <webElementGuid>fd5e1dfc-4531-4a48-a71a-55ef1e51c4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='图片来源'])[1]/preceding::div[7]</value>
      <webElementGuid>33bb7a70-0fec-4f89-8b40-89034f0a5e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='疾诊室 | 冬天小儿患病多，医疗口诀来帮忙'])[1]/preceding::div[10]</value>
      <webElementGuid>be549519-e249-40ce-a889-56cd87f8153c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='知道啦']/parent::*</value>
      <webElementGuid>fd93d31f-509b-45c4-b448-d135dd96218b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>39e80568-0d6d-444b-bf0b-4557b24578f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
            知道啦
        ' or . = '
            知道啦
        ')]</value>
      <webElementGuid>ed3fbd71-7e19-4f3a-8d33-70a62d0b5179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
