<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__upload-pic</name>
   <tag></tag>
   <elementGuidId>061004f8-ff78-4cb3-813d-920d996aaeae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.upload-pic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='上传图片']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14789fed-902b-4e42-8fab-1b8660c34f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>424073e3-b78a-446b-8061-8007d5b8a9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-pic</value>
      <webElementGuid>14310e6c-8017-4f60-80dd-3071c1ed966d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>上传图片</value>
      <webElementGuid>1d716f99-287f-4757-9853-564c8e733dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;soutu-layer new-pmd&quot;]/div[@class=&quot;soutu-state-normal&quot;]/div[@class=&quot;upload-wrap&quot;]/input[@class=&quot;upload-pic&quot;]</value>
      <webElementGuid>2c31f432-9d53-47ec-9e92-be4cc910a6e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='上传图片']</value>
      <webElementGuid>b90ef2a0-9b11-4504-a4d3-0cdf162e1c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[2]/div[2]/input</value>
      <webElementGuid>10699c92-fe06-4484-8924-51e731a58a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0ce38992-37ba-4e06-bb98-7cb0cbe9a3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file']</value>
      <webElementGuid>7fcf3c82-c0ca-4f7e-8714-fe19a56a6dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
