<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__graph-searchtext-box-icon</name>
   <tag></tag>
   <elementGuidId>48a534fe-78ea-4dc7-b025-8a2e8e50cc77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.graph-searchtext-box-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div/div[3]/div/div[1]/span/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7d34874-a99e-4e90-9031-f7483fba87fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>graph-searchtext-box-icon</value>
      <webElementGuid>98d9c70e-4ef2-4f5a-9123-7b21e87225e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;card-page&quot;]/div[@class=&quot;graph-result-card&quot;]/div[@class=&quot;graph-similar graph-container&quot;]/div[@class=&quot;general-title-cont&quot;]/span[@class=&quot;graph-searchtext&quot;]/span[@class=&quot;graph-searchtext-box&quot;]/span[@class=&quot;graph-searchtext-box-icon&quot;]</value>
      <webElementGuid>747ad178-5c00-4c20-8d59-a8084fc2046c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/span/span/span[2]</value>
      <webElementGuid>ed5eb552-44c0-4678-b510-dd818b128148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span[2]</value>
      <webElementGuid>487122e2-55f5-4c31-80a8-417015253ecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
