<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__soutu-url-kw</name>
   <tag></tag>
   <elementGuidId>bce7e09f-c57e-43af-950f-8c827e880a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='soutu-url-kw']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#soutu-url-kw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>523c756d-d2f8-49d8-9ebd-29de6f5aba59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>soutu-url-kw</value>
      <webElementGuid>3c11379b-f480-491e-ac49-3435dce9d12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>soutu-url-kw</value>
      <webElementGuid>45324e5b-f92b-4648-9cd5-e4e466200228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>0fad1d83-854c-4cde-9e8b-a917db0a4f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8671da76-bba3-4bae-83f0-f28809dba74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>在此处粘贴图片网址</value>
      <webElementGuid>99d3ab33-ce3f-48ff-aaa9-f8d8760a0c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;soutu-url-kw&quot;)</value>
      <webElementGuid>ea0b5b92-fbaf-4eb7-a07a-dcfcf8a88274</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='soutu-url-kw']</value>
      <webElementGuid>3033f57d-ebf7-4a16-a252-c5ba9e4632f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/span/input</value>
      <webElementGuid>bcbe593b-70c0-471f-87b8-0f8889deacde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f329f721-640c-4d0f-93b9-7ecdeebcc213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'soutu-url-kw' and @placeholder = '在此处粘贴图片网址']</value>
      <webElementGuid>36312304-0c69-44ca-be65-aba18019d445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
